name: tdlib-build

on:
  push:
    paths:
      - '.github/workflows/td-version.json'
      - '.github/workflows/build-tdlib.yml'

jobs:
  build-windows-x64:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2

      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: '.github/workflows/td-version.json'
          prefix: td

      - name: clone
        run: |
          git clone https://github.com/tdlib/td.git
          cd td
          git checkout ${{ env.td_commit_hash }}
          git show --summary

      - name: setup vcpkg
        run: |
          cd td
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          git checkout cd5e746ec203c8c3c61647e0886a8df8c1e78e41
          ./bootstrap-vcpkg.bat
          ./vcpkg.exe install gperf:x64-windows openssl:x64-windows zlib:x64-windows

      - name: build
        run: |
          cd td
          mkdir build
          cd build
          cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=../tdlib -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
          cmake --build . --target install --config Release

#      - name: fake build
#        run: |
#          mkdir -p td/tdlib/bin
#          echo test > td/tdlib/bin/libcrypto-3-x64.dll
#          echo test > td/tdlib/bin/libssl-3-x64.dll
#          echo test > td/tdlib/bin/tdjson.dll
#          echo test > td/tdlib/bin/zlib1.dll

      - name: zip
        run: |
          cd td/tdlib/bin
          ls
          mv libcrypto-3-x64.dll libcrypto-1_1.dll
          mv libssl-3-x64.dll libssl-1_1.dll
          7z a -tzip dlls.zip libcrypto-1_1.dll libssl-1_1.dll tdjson.dll zlib1.dll

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: windows-x64-${{ env.td_version }}-${{ env.td_commit_hash }}
          name: Windows x64 ${{ env.td_version }}-${{ env.td_commit_hash }}
          body: https://github.com/tdlib/td/tree/${{ env.td_commit_hash }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'td/tdlib/bin/dlls.zip'

